name: spack build test

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repo to ./recipes 🥣
        uses: actions/checkout@v2
        with:
          path: ./recipes
          fetch-depth: 1

      - name: Checkout spack to ./spack 🥣
        uses: actions/checkout@v2
        with:
          repository: spack/spack
          ref: develop
          path: ./spack
          fetch-depth: 1

      - name: List installed packages 🔍
        run: |
          source spack/share/spack/setup-env.sh
          spack find -lvvx

      - name: Build 🔨
        run: |
            source spack/share/spack/setup-env.sh
            DIFF="$( cd recipes; git diff --name-only origin/main main specs )"
            for file in ${DIFF}; do
              spack install --fail-fast $(<${file})
            done
